### ISSUE TITLE
Persistence 

### ISSUE THREAD

**Issue by honeyfairy** [hatamiarash7/Mikrotik-Exporter#15]
I'm using the following line to run this:
`./mikrotik-exporter_linux_amd64 --config-file=config.yml`

So if server restarts how can I have it start automatically?

**Comment by hatamiarash7** [comment]
The simple way is [Docker](https://www.docker.com/) and the hard way is create startup script: 

```
$ sudo nano /etc/rc.local

#!/bin/sh
/path-to-your-script/your-scipt-name.sh

$ sudo chmod 755 /etc/rc.local
$ sudo systemctl start rc-local
```

You can find many examples here : [How to run a shell script at startup](https://stackoverflow.com/questions/12973777/how-to-run-a-shell-script-at-startup)
