### ISSUE TITLE
Get serial number [Enhancement]

### ISSUE THREAD

**Issue by irishburlybear** [hatamiarash7/Mikrotik-Exporter#17]
Add option for either a label or value (or both)

**Comment by hatamiarash7** [comment]
What do you need exactly? Serial number of Mikrotik devices in Prometheus?

**Comment by irishburlybear** [comment]
Yes... If I knew golang I would attempt to contribute.

**Comment by hatamiarash7** [comment]
Your request is done. Version `1.2.4` will be released in a few minutes. Related PR : #18
