### ISSUE TITLE
Show usage

### ISSUE THREAD

**Issue by honeyfairy** [hatamiarash7/Mikrotik-Exporter#21]
Is it possible to see Usage statistics per interface?
For example, I would like to see how much traffic passed through ether1 for the past 24 hours

I do not see this currently

**Comment by hatamiarash7** [comment]
Yes. You can filter metrics by labels : 

```
mikrotik_interface_rx_byte{address="$node", interface="ether1"}
```

And for **past 24 hours** ... Change `Absolute time range` to `Last 24 hours` in graph

**Comment by honeyfairy** [comment]
Actually I meant: Amount of bandwidth Used.
So, I want to see how many gigabytes was used on that interface in the past 24 hours, is this possible?

This is what i see currently:
![Uploading traffic.PNG…]()

**Comment by hatamiarash7** [comment]
It's an hourly report ... change the range to daily

**Comment by honeyfairy** [comment]
But I still do not see how much bandwidth was used. I just see the speed history. not the **_amount_**

**Comment by hatamiarash7** [comment]
Let me check that

**Comment by honeyfairy** [comment]
> Let me check that

Thank you, will await your reply
