### ISSUE TITLE
Help with Grafana

### ISSUE THREAD

**Issue by jaredstoker** [hatamiarash7/Mikrotik-Exporter#22]
Noob Grafana user here. I was able to setup the mikrotik exporter and I show data at localhost:9436/metrics And I added the Grafana dashboard via the JSON, but I'm getting no data to show up in the dashboard. Is this something simple I'm missing? I only have prometheus as the data source. Do I need another one for the mikrotik data?

**Comment by hatamiarash7** [comment]
1- Try to import Grafana dashboard with ID
2- Did you select the right node?

**Comment by jaredstoker** [comment]
Thanks for the quick response. I forgot to add the exporter in my Prometheus configuration file. I can add a section to the readme for that step for beginners like me. 
I did run into an issue trying to build out a service so that the mikrotik exporter would auto start. Maybe that’s outside the scope of this but it might be helpful.
