### ISSUE TITLE
Docker image for ARM/ARM64 arch

### ISSUE THREAD

**Issue by nidr0x** [hatamiarash7/Mikrotik-Exporter#3]
@hatamiarash7 Could you upload also in your Dockerhub repository images for ARM and ARM64 arch, please?

**Comment by hatamiarash7** [comment]
@nidr0x Sure ... It's in progress for the next update. Feel free to send PR if you want to collaborate .

**Comment by hatamiarash7** [comment]
The multi-arch manifest uploaded :

https://hub.docker.com/r/hatamiarash7/mikrotik-exporter/tags

Test and submit another issue if you have any problem about new architectures.

**Comment by nidr0x** [comment]
Thanks @hatamiarash7
