### ISSUE TITLE
/app/start.sh: permission denied

### ISSUE THREAD

**Issue by elcidowneador** [hatamiarash7/Mikrotik-Exporter#4]
Hi, i'm trying to run under ARM 32 bits and im getting this error:

`"oci runtime error: container_linux.go:265: starting container process caused "exec: /app/start.sh: permission denied"`

This is because `chmod +x` is not done when container is built? Thanks

**Comment by hatamiarash7** [comment]
Can you check and send a PR ?

**Comment by elcidowneador** [comment]
I'm trying to build but it's failing:

`      docker build -t hatamiarash7/mikrotik-exporter:arm32v7 --build-arg BASE_ARCH=arm32v7 --build-arg BINARY_ARCH=arm .

[+] Building 2.0s (7/7) FINISHED
 => [internal] load .dockerignore                                                                                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                                                                                         0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                     0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/arm32v7/debian:9.12-slim                                                                                                                                                                      1.9s
 => [internal] load build context                                                                                                                                                                                                        0.0s
 => => transferring context: 65B                                                                                                                                                                                                         0.0s
 => CANCELED [1/3] FROM docker.io/arm32v7/debian:9.12-slim@sha256:6aac188bc15bac908192685068ef8512a2e51b5eb1138b663e9e33d1d98ade4b                                                                                                       0.0s
 => => resolve docker.io/arm32v7/debian:9.12-slim@sha256:6aac188bc15bac908192685068ef8512a2e51b5eb1138b663e9e33d1d98ade4b                                                                                                                0.0s
 => CACHED [2/3] COPY scripts/start.sh /app/                                                                                                                                                                                             0.0s
 => ERROR [3/3] COPY dist/mikrotik-exporter_linux_arm /app/mikrotik-exporter                                                                                                                                                             0.0s
------
 > [3/3] COPY dist/mikrotik-exporter_linux_arm /app/mikrotik-exporter:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/dist/mikrotik-exporter_linux_arm" not found: not found
`

What i'm doing wrong, mate?

**Comment by hatamiarash7** [comment]
You should build the Go project first. `Dockerfile` use the generated binaries ... look at `Makefile` : 

https://github.com/hatamiarash7/Mikrotik-Exporter/blob/5561f0a81647a2d4fb4ea2277703948b5004b51a/Makefile#L28

We can generate binaries for ant OS/Arch using [gox](https://github.com/mitchellh/gox). For example, you can use this command to build binary for an ARM arch in linux : 

```bash
gox -os="linux" -arch="arm" -output "dist/mikrotik-exporter_linux_arm"
```

**Comment by elcidowneador** [comment]
Thanks! finally i was able to solve it by adding `chmod +x /app/start.sh`. I will make a PR soon.
